### ISSUE TITLE
Wrong signature with form CSRF token 

### ISSUE THREAD

**Issue by denostr** [bookin/yii2-wallet-one#3]
Если в конфиге установлены следующие настройки
`array('components' => array('request' => array('enableCsrfValidation'=>true))))`
форма будет вместе с параметрами подставлять токен, и сигнатура будет не верная.

Для того что избежать этого, перед инициализацией формы надо выполнить следующее
`Yii::app()->request->enableCsrfValidation = false;`

Думаю стоит добавить это в README.md

**Comment by bookin** [comment]
Вы правы. И, по-моему, даже если не установлены в конфигурации, по умолчанию в форму добавляется CSRF токен. В `WalletOneButton::widget()` есть строка `\Yii::$app->request->enableCsrfValidation = false;`, в остальном, да, необходимо самому учитывать нюанс.

Есть еще пару моментов которых хочу внести в README, но все руки не доходят.
