### ISSUE TITLE
Указать номер версии

### ISSUE THREAD

**Issue by Doka-NT** [bookin/yii2-wallet-one#4]
Добрый день!

Создайте плз новую версию (релиз) вашей библиотеки, т.к. зависеть от dev-master не очень хорошо)

**Comment by bookin** [comment]
Просто зарелизеть? Или вы намекаете что в спи произошли изминения?)

**Comment by Doka-NT** [comment]
Просто зарелизить)
Хочется быть уверенным, что при composer update изменения из dev-master не устроят сюрприза.

**Comment by bookin** [comment]
https://github.com/bookin/yii2-wallet-one/releases/tag/1.0.0

**Comment by Doka-NT** [comment]
Thanks! Great!

**Comment by bookin** [comment]
You are welcome.
